#action.yml
name: fibBot
description: 'Enable Fibonacci series up to max_threshold'
inputs:
  enable_fib: #id of the input
    description: 'Do you want to enable the fibBot ?'
    required: false
    default: 'true'
  max_threshold: #id of the input
    description: 'The maximum threshold for the Fibonacci series'
    required: false
    default: '100'
runs:
  using: 'docker'
  image: 'docker://Dockerfile'
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}