name: fibBot

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run Rust code
        uses: ./
        id: program_output
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Dockerfile output: ${{ steps.program_output.outputs.output }}
          reactions: eyes, rocket
